---
classes:
  - exercises:
      - file: "../examples/bom.md"
        title: "bom"
        syntax: "md-extended"
      - file: "../examples/complex-yaml.md"
        title: "complex-yaml"
        syntax: "md-extended"
      - file: "../examples/dashes-seperator.md"
        title: "dashes-seperator"
        syntax: "md-extended"
      - file: "../examples/dots-ending.md"
        title: "dots-ending"
        syntax: "md-extended"
      - file: "../examples/missing-body.md"
        title: "missing-body"
        syntax: "md-extended"
      - file: "../examples/no-front-matter.md"
        title: "no-front-matter"
        syntax: "md-extended"
      - file: "../examples/unsafe.md"
        title: "unsafe"
        syntax: "md-extended"
      - file: "../examples/wrapped-text.md"
        title: "wrapped-text"
        syntax: "md-extended"
      - file: "../examples/yaml-seperator.md"
        title: "yaml-seperator"
        syntax: "md-extended"

